# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 817f4cc6c798af2b9d7e463891db08f2eff353c2d589b4b9aed3d86307842ccf337735741c180063e4e945a24ee8ee1f11c402dbc5cbb3724355f4c4d295e7d4

test:
  secret_key_base: bffac4fb9419d3c513a976443437a5804ca5694faa9ddb08bff5736899912d92afcd96f0d76dc94933ffc55da844957dbcc3be80dc9e39a83585ec0b25b5b9e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
